export const PRIMARY_COLOR = "#F7D22D";
export const CONTAINED_BUTTON_BG_HOVER_COLOR = "#EFCC00";
export const TEXT_BUTTON_COLOR = "#696F7A";
export const OUTLINED_BUTTON_COLOR = "#0E0C0D";
export const OUTLINED_BUTTON_BORDER_COLOR = "#E3ECF5";
